import { ProductFittings } from "@/types/product/productFittings";

// export const CONSTANT_PRODUCT_FITTING: ProductFittings[] = [
//   {
//     id: 1,
//     productDetailProductId: 1,
//     name: "Arroz",
//     description: "Arroz blanco de grano largo",
//     quantity: 0,
//     price: 0,
//     isCountable: false,
//     imageUrl: "./images/product/fittings/arroz-01.jpg",
//     createdAt: new Date().toISOString(),
//     createdBy: "admin",
//     state: true,
//   },
//   {
//     id: 2,
//     productDetailProductId: 1,
//     name: "Fideo",
//     description: "Fideo espagueti número 5",
//     quantity: 0,
//     price: 0,
//     isCountable: false,
//     imageUrl: "./images/product/fittings/fideo-01.jpg",
//     createdAt: new Date().toISOString(),
//     createdBy: "admin",
//     state: true,
//   },
//   {
//     id: 3,
//     productDetailProductId: 1,
//     name: "Papa",
//     description: "Papa blanca grande",
//     quantity: 0,
//     price: 0,
//     isCountable: false,
//     imageUrl: "./images/product/fittings/papas-fritas-01.webp",
//     createdAt: new Date().toISOString(),
//     createdBy: "admin",
//     state: true,
//   },
//   {
//     id: 4,
//     productDetailProductId: 1,
//     name: "Ensalada",
//     description: "Ensalada fresca de lechuga, tomate y cebolla",
//     quantity: 0,
//     price: 0,
//     isCountable: false,
//     imageUrl: "./images/product/fittings/ensalada-01.jpg",
//     createdAt: new Date().toISOString(),
//     createdBy: "admin",
//     state: true,
//   },
// ];
